project_id = "apidixbcujmqhxicjqut"

[functions.ai-evaluation]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.dynamic-question-generator]
verify_jwt = true

[functions.gpt5-chat]
verify_jwt = true
